### ISSUE TITLE
list of software requirements

### ISSUE THREAD

**Issue by martinjrobins** [OxfordRSE/rsd-engineeringcourse#6]
For the UNIQ+ course we will have desktop computers for the students, we need to get a list of software requirements for the IT team to install on these computers before the course starts.

Due: early June

**Comment by iamleeg** [comment]
I've put a setup guide in the repo: https://github.com/OxfordRSE/rsd-engineeringcourse/tree/master/00prestudy

**Comment by martinjrobins** [comment]
perfect, thanks!
